version: '3'

services:
  db:
    image: db
    restart: always
    volumes:
    - ./db/data:/var/lib/postgresql/data
  backend:
    image: backend
    restart: always
    command: sh /docker-entrypoint.sh
    depends_on:
      - db
    ports:
      - "8080:8080"
  frontend:
    image: frontend
    ports:
      - "5000:80"
    command: /bin/bash -c "exec nginx -g 'daemon off;'"
    depends_on:
      - backend
